## 1.数组定义、常见属性

引入一下Numpy模块，Numpy的数组使用可以查看一下帮助文档

In [1]:
# 导入Numpy模块
import numpy as np

In [2]:
help(np.array)

Help on built-in function array in module numpy.core.multiarray:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.  This argument can only be used to 'upcast' the array.  For
        downcasting, use the .astype(t) method.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K'

### 1.1.通过List创建数组

`np.array(list)`

**注意**：

`print(np.array([1,2,3,4,5]))`和`np.array([1,2,3,4,5])`

**在交互摸索下显示是稍微有点区别的**，千万别以为是不一样的东西



In [3]:
# 构造一个list1
list1 = list(range(10))
print(list1)

# 通过List创建一个一维数组
array1 = np.array(list1)

print(array1)
type(array1)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0 1 2 3 4 5 6 7 8 9]


numpy.ndarray

In [4]:
# 你直接写也一样
test_array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

print(test_array)
type(test_array)

[0 1 2 3 4 5 6 7 8 9]


numpy.ndarray

In [5]:
# 创建一个嵌套列表
list2 = [list1,list1]
print(list2)

# 通过嵌套列表创建二维数组
array2 = np.array(list2)
print(array2)

[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]
[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]


In [6]:
# 创建3维数组
array3 = np.array([
    [[1,2,3],[4,5,6],[7,8,9]],
    [[1,2,3],[4,5,6],[7,8,9]]
])

print(array3)
type(array3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


numpy.ndarray

In [7]:
################### 扩展部分 ########################

# 其实你通过元组创建也一样，只是官方演示文档里面用的是list

# 逆天推荐使用列表（和官方文档一致嘛）

In [8]:
# 一维数组
np.array((1,2,3,4,5))

array([1, 2, 3, 4, 5])

In [9]:
# 都是一个数组，你print和直接输入名字是稍微有点区别的
# 千万别以为是不一样东西

print(np.array((1,2,3,4,5)))

[1 2 3 4 5]


In [10]:
# 二维数组
np.array(((1,2,3),(4,5,6)))

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
# 二维数组，这种方式也一样
np.array(([1,2,3],[4,5,6]))

array([[1, 2, 3],
       [4, 5, 6]])

### 1.2.常用属性

`ndim` 查看数组维度

`shape` 查看数组形状

`size` 查看数组含有多少元素（行*列）

`dtype` 查看元素的数据类型

In [12]:
help(array2)

Help on ndarray object:

class ndarray(builtins.object)
 |  ndarray(shape, dtype=float, buffer=None, offset=0,
 |          strides=None, order=None)
 |  
 |  An array object represents a multidimensional, homogeneous array
 |  of fixed-size items.  An associated data-type object describes the
 |  format of each element in the array (its byte-order, how many bytes it
 |  occupies in memory, whether it is an integer, a floating point number,
 |  or something else, etc.)
 |  
 |  Arrays should be constructed using `array`, `zeros` or `empty` (refer
 |  to the See Also section below).  The parameters given here refer to
 |  a low-level method (`ndarray(...)`) for instantiating an array.
 |  
 |  For more information, refer to the `numpy` module and examine the
 |  methods and attributes of an array.
 |  
 |  Parameters
 |  ----------
 |  (for the __new__ method; see Notes below)
 |  
 |  shape : tuple of ints
 |      Shape of created array.
 |  dtype : data-type, optional
 |      Any objec

In [13]:
# 查看维度
print(array1.ndim)
print(array2.ndim)
print(array3.ndim)

1
2
3


In [14]:
# 数组的形状，Tuple类型
print(array1.shape)
print(array2.shape) # 2行10列
print(array3.shape)

(10,)
(2, 10)
(2, 3, 3)


In [15]:
# 查看总共多少元素（行*列）
array2.size

20

In [16]:
# 查看元素的数据类型
array2.dtype

dtype('int64')

In [17]:
################### 扩展部分 ########################

In [18]:
# Array元素类型都一致，如果不一致会以最大兼容来初始化

np.array([[1,2,3],[4,5,6.0]]) # 都变成Float类型了

array([[1., 2., 3.],
       [4., 5., 6.]])

In [19]:
# 指定类型
np.array([[1,2,3],[4,5,6]],dtype=float)

array([[1., 2., 3.],
       [4., 5., 6.]])

In [20]:
# 行元素的个数不一致的测试

test_list = [[1],[1,2]]
print(test_list)

test_array = np.array(test_list)

print(test_array)

print(test_array.dtype) # 全部变成了object

[[1], [1, 2]]
[list([1]) list([1, 2])]
object


### 1.3.通过arange和reshape创建数组

`range()`返回的是`range`对象，而 **`np.arange()`返回的是`numpy.ndarray() `**

两者都可以进行迭代，而`np.nrange`还是一个序列，可被当做向量使用

`range()`不支持步长为小数, **`np.arange()`支持步长为小数**

如果这些基础类型还不是很清楚，可以看我之前写的文章：<a href="https://www.cnblogs.com/dunitian/p/4822808.html#ai" target="_blank">https://www.cnblogs.com/dotnetcrazy/p/9155310.html</a>

---

**多维数组创建**：（reshape的 **行x列 != 元素个数** 就会报错）

创建3行5列的数组：`np.arange(15).reshape((3,5))`

告诉它多少列，自动求行：`np.arange(20).reshape((-1,5))`

告诉它多少行，自动求列：`np.arange(20).reshape((4,-1))`

In [21]:
help(np.arange)

Help on built-in function arange in module numpy.core.multiarray:

arange(...)
    arange([start,] stop[, step,], dtype=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range <http://docs.python.org/lib/built-in-funcs.html>`_ function,
    but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use ``linspace`` for these cases.
    
    Parameters
    ----------
    start : number, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : number
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and

In [22]:
list(range(5))

[0, 1, 2, 3, 4]

In [23]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [24]:
type(range(1,10))

range

In [25]:
# 用法和range差不多
array1 = np.arange(1,10) # [1,10)

print(array1)

type(array1)

[1 2 3 4 5 6 7 8 9]


numpy.ndarray

In [26]:
# 可以直接迭代
for i in array1:
    print(i,end=' ')

1 2 3 4 5 6 7 8 9 

In [27]:
# Python里面的range不支持步长为小数
range(1,10,0.5)

TypeError: 'float' object cannot be interpreted as an integer

In [28]:
# 支持步长为小数
np.arange(1,10,0.5) # step为0.5

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [29]:
################### 开始变化 ########################

In [30]:
help(array1.reshape)

Help on built-in function reshape:

reshape(...) method of numpy.ndarray instance
    a.reshape(shape, order='C')
    
    Returns an array containing the same data with a new shape.
    
    Refer to `numpy.reshape` for full documentation.
    
    See Also
    --------
    numpy.reshape : equivalent function
    
    Notes
    -----
    Unlike the free function `numpy.reshape`, this method on `ndarray` allows
    the elements of the shape parameter to be passed in as separate arguments.
    For example, ``a.reshape(10, 11)`` is equivalent to
    ``a.reshape((10, 11))``.



In [31]:
# 创建2维数组，参数传元组比较合适（官方案例也是元组）
np.arange(1,10,0.5).reshape((2,9))

array([[1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ],
       [5.5, 6. , 6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5]])

In [32]:
# 3行5列
np.arange(15).reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [33]:
# 告诉它多少列，自动求行
np.arange(20).reshape((-1,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [34]:
# 告诉它多少行，自动求列
np.arange(20).reshape((4,-1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [35]:
# reshape的 **行x列 != 元素个数** 就会报错
np.arange(20).reshape(3,7)

ValueError: cannot reshape array of size 20 into shape (3,7)

## 2.数组常用方法

### 2.1.数组元素的获取

基础用法之前讲过，可以回顾一下：<a href="https://www.cnblogs.com/dotnetcrazy/p/9114691.html#2.1.Python" target="_blank">https://www.cnblogs.com/dotnetcrazy/p/9114691.html#2.1.Python</a>

简写：**`array_name[行,列]`** ，通用写法：`array_name[行][列]`（**行列都是从0开始**）

In [36]:
# 先用熟悉的一维数组
array1 = np.arange(10)

print(array1)

[0 1 2 3 4 5 6 7 8 9]


In [37]:
# 取第一个元素
array1[0]

0

In [38]:
# 取最后一个元素
array1[-1]

9

In [39]:
# 取第二个元素
array1[1]

1

In [40]:
# 取倒数第二个元素
array1[-2]

8

In [41]:
################### 二维数组 ########################

In [42]:
test_array = np.array([[1,2,3],[4,5,6]])

print(test_array)

[[1 2 3]
 [4 5 6]]


In [43]:
# 获取元素4（行列都是从0开始）
test_array[1][0]

4

In [44]:
# 获取元素4 简写
test_array[1,0]

4

In [45]:
# 获取第一行最后一个
test_array[0,-1]

3

In [46]:
# 获取最后一行倒数第二个元素
test_array[-1,-2]

5

### 2.2.多维数组的切片用法

**`array_name[行切片,列切片]`** eg：`test_array[1:3,1:3]`==> 取索引为1,2的行；取索引为1,2的列

基础用法之前讲过，可以回顾一下：<a href="https://www.cnblogs.com/dotnetcrazy/p/9155310.html#1.7.列表切片" target="_blank">https://www.cnblogs.com/dotnetcrazy/p/9155310.html#1.7.列表切片</a>

In [47]:
# 先用熟悉的一维数组
array1 = np.arange(100)

print(array1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [48]:
# 全部取出来
array1[::]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [49]:
# 从索引为1～最后
array1[1::]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [50]:
################### 切片开始 ########################

In [51]:
# 从第二个元素取到最后,step为10
array1[1::10]

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [52]:
# [1,5) 从下标1取到下标4,下标为5的取不到
array1[1:5]

array([1, 2, 3, 4])

In [53]:
# 取下标为1～倒数第二个元素（end_index取不到）
array1[1:-1]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [54]:
# 取前10个
array1[:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
# 取最后10个，可以理解为从索引-5的元素到最后
array1[-10:]

array([90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [56]:
# 前11~20（eg：第二页）
array1[10:20]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [57]:
# 取80~90（eg:倒数第二页）
array1[-20:-10]

array([80, 81, 82, 83, 84, 85, 86, 87, 88, 89])

In [58]:
# 前20个数，每两个取一个（eg:隔行换样式）
array1[:20:2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [59]:
# 所有数每10个取一个（eg:test的时候十里挑一）
array1[::10]

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [60]:
################### 二维数组 ########################

In [61]:
# 生成一个多维数组
test_array = np.arange(15).reshape(3,5)

print(test_array)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [62]:
# [行切片，列切片]
# 行：取第2行到最后，列：取第3列到最后
test_array[1:,2:]

array([[ 7,  8,  9],
       [12, 13, 14]])

In [63]:
# 所有行，最后一列
test_array[:,-1:]

array([[ 4],
       [ 9],
       [14]])

In [64]:
# 所有行，索引[0,2)列
test_array[:,:2]

array([[ 0,  1],
       [ 5,  6],
       [10, 11]])

In [65]:
# 索引1的行，索引1的列
test_array[1:2,1:2]

array([[6]])

In [66]:
# 上面的等同于test_array[1][1]
print(test_array[1,1])

6


In [67]:
# 取索引为1,2的行；取索引为1,2的列
test_array[1:3,1:3]

array([[ 6,  7],
       [11, 12]])

### 2.3.zeros创建全为0的矩阵

`np.zeros(tuple)` 默认类型是float

\begin{bmatrix}
0&0&0 \\
0&0&0 \\
0&0&0
\end{bmatrix}

In [1]:
# 导入Numpy模块
import numpy as np

In [2]:
help(np.zeros)

Help on built-in function zeros in module numpy.core.multiarray:

zeros(...)
    zeros(shape, dtype=float, order='C')
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional
        Whether to store multidimensional data in C- or Fortran-contiguous
        (row- or column-wise) order in memory.
    
    Returns
    -------
    out : ndarray
        Array of zeros with the given shape, dtype, and order.
    
    See Also
    --------
    zeros_like : Return an array of zeros with shape and type of input.
    ones_like : Return an array of ones with shape and type of input.
    empty_like : Return an empty array with shape and type of input.
    ones : Return a new array setting v

In [3]:
# 一维
np.zeros(5) # 完整写法：np.zeros((5,))

array([0., 0., 0., 0., 0.])

In [4]:
# 可以指定类型
array1 = np.zeros(5,dtype=int)

print(array1)
type(array1)

[0 0 0 0 0]


numpy.ndarray

In [5]:
# 二维
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [6]:
# 三维 ==> 可以这么理解，2个2*5（2行5列）的矩阵
np.zeros((2,2,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [7]:
################### 扩展部分 ########################

In [8]:
# 建议用元组，官方文档都是元组，而且shape返回类型就是元组
array1 = np.zeros([2,3])
print(array1)
type(array1)
print(array1.shape) # shape返回类型就是元组

[[0. 0. 0.]
 [0. 0. 0.]]
(2, 3)


### 2.4.ones创建全为1的矩阵

`np.ones(tuple)` 用法和`np.zeros(tuple)`差不多

\begin{bmatrix}
1&1&1 \\
1&1&1 \\
1&1&1
\end{bmatrix}

In [9]:
help(np.ones)

Help on function ones in module numpy.core.numeric:

ones(shape, dtype=None, order='C')
    Return a new array of given shape and type, filled with ones.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional
        Whether to store multidimensional data in C- or Fortran-contiguous
        (row- or column-wise) order in memory.
    
    Returns
    -------
    out : ndarray
        Array of ones with the given shape, dtype, and order.
    
    See Also
    --------
    zeros, ones_like
    
    Examples
    --------
    >>> np.ones(5)
    array([ 1.,  1.,  1.,  1.,  1.])
    
    >>> np.ones((5,), dtype=int)
    array([1, 1, 1, 1, 1])
    
    >>> np.ones((2, 1))
    array([[ 1.],
           [ 1.]])
    
    >>> s = (2,2)
    >>> np.ones(s)
    ar

In [10]:
# 一维
np.ones(5) # 完整写法 np.ones((5,))

array([1., 1., 1., 1., 1.])

In [11]:
# 可以指定类型
array1 = np.ones(5,dtype=int)

print(array1)
type(array1)

[1 1 1 1 1]


numpy.ndarray

In [12]:
# 二维，传一个shape元组
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
# 三维 可以理解为两个二维数组
np.ones((2,2,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

### 2.5.eye创建单位矩阵

先普及一个数学基础：**任何`矩阵` x `单位矩阵` 都等于其`本身`**

单位矩阵是个方阵（行列相等），从左上角到右下角的对角线（称为主对角线）上的元素均为1。其他全都为0，eg:

\begin{bmatrix}
1&0&0 \\
0&1&0 \\
0&0&1
\end{bmatrix}

用 **`np.eye()`** 来定义(eye：眼睛)

扩展：`np.eye(rows,columns=rows)`

In [14]:
help(np.eye)

Help on function eye in module numpy.lib.twodim_base:

eye(N, M=None, k=0, dtype=<class 'float'>, order='C')
    Return a 2-D array with ones on the diagonal and zeros elsewhere.
    
    Parameters
    ----------
    N : int
      Number of rows in the output.
    M : int, optional
      Number of columns in the output. If None, defaults to `N`.
    k : int, optional
      Index of the diagonal: 0 (the default) refers to the main diagonal,
      a positive value refers to an upper diagonal, and a negative value
      to a lower diagonal.
    dtype : data-type, optional
      Data-type of the returned array.
    order : {'C', 'F'}, optional
        Whether the output should be stored in row-major (C-style) or
        column-major (Fortran-style) order in memory.
    
        .. versionadded:: 1.14.0
    
    Returns
    -------
    I : ndarray of shape (N,M)
      An array where all elements are equal to zero, except for the `k`-th
      diagonal, whose values are equal to one.
    
  

In [15]:
# 定义一个2行的单位矩阵（列默认和行一致）
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [16]:
array1 = np.eye(3,dtype=int)

print(array1)
type(array1)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


numpy.ndarray

In [17]:
# 定义一个5行5列的单位矩阵
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
################### 扩展部分 ########################

In [19]:
# 可以创建np.eye(rows,columns=rows)
# 但是这种就不是单位矩阵了（单位矩阵是个方阵）
np.eye(2,3)

array([[1., 0., 0.],
       [0., 1., 0.]])

### 2.6.